### ISSUE TITLE
[RFC] Drop support for pass-based optimization

### ISSUE THREAD

**Issue by chelini** [plaidml/tpp-mlir#134]
As you know our optimization flow is moving toward transform. Today we have two optimization flows: 1. transform, 2. pass-based. I would like to remove support for the pass-based one and use transform only. This would allow to avoid duplicate test, and drop quite significant amount of c++.
Example:
`convolution2d_nchw_fchw.mlir` is a subset of `transform-pack.mlir`
`-decompose-conv-to-matmul-or-brgemm="enable-brgemm=true block-factors=32,32"` is a quite involved pass that can be expressed as a composition of transform ops: https://github.com/plaidml/tpp-sandbox/blob/38529869d79938299a12d2e327b925a85d8e35f1/test/TPP/transform/transform-convolutions.mlir#L38

What do you think?

**Comment by rengolin** [comment]
The main concern I have is that, today, we can get a generic IR from a front-end and generate TPP code. If we only have the transform pass, we won't do anything without transform blocks, but we also won't have generic transform blocks that replace the current passes.

So, to be able to drop support for pass-based, we need to replace it with equal functionality, that does not depend on a "future tool" that will generate the transform blocks.

Two simple ways to achieve that would be:
1. Have a "library" of transforms in MLIR form that we append to every module before running the transform pass. This is simple, but may conflict if we currently have different strategies for different shapes of the same op (in the passes).
2. Have a pass that generates the transform blocks based on the same heuristics that we have today on the passes themselves. This is more complex, but also allows us to have tailored transforms and an entry point for the "future tool" to introduce its own transforms.

We may be able to move the current extra C++ code into the pre-transform pass (2), and this is probably a good reason to do that now rather than simplify too much (1) and then have to fish that code from archives later.

**Comment by chelini** [comment]
> The main concern I have is that, today, we can get a generic IR from a front-end and generate TPP code. If we only have the transform pass, we won't do anything without transform blocks, but we also won't have generic transform blocks that replace the current passes.
> 
> So, to be able to drop support for pass-based, we need to replace it with equal functionality, that does not depend on a "future tool" that will generate the transform blocks.
> 
> Two simple ways to achieve that would be:
> 
> 1. Have a "library" of transforms in MLIR form that we append to every module before running the transform pass. This is simple, but may conflict if we currently have different strategies for different shapes of the same op (in the passes).

I would expect indeed to have a "library" of transform ops general enough to cover different strategies we may want to apply. Usually similar-looking code need to be optimized in the same way. It would be similar to have a bunch of hardcoded passes, so what is your concern? 

> 2. Have a pass that generates the transform blocks based on the same heuristics that we have today on the passes themselves. This is more complex, but also allows us to have tailored transforms and an entry point for the "future tool" to introduce its own transforms.

I was not thinking this :)

> 
> We may be able to move the current extra C++ code into the pre-transform pass (2), and this is probably a good reason to do that now rather than simplify too much (1) and then have to fish that code from archives later.

**Comment by rengolin** [comment]
If we can do the exact same transform for each match we make, then the static library works fine. But if the match isn't precise enough (and we get away with it because we have hand-coded blocks on our tests).

Looking at the `test/TPP/transform` tests:
* `blocking_factor` is usually 32, but some are 2, others are 200
* `tile_sizes` depend on the number of dimensions, so we'll have to have a block for each case
* `iterator_interchange` has many different shapes and ranks in our tests

**Comment by chelini** [comment]
We can have an exact match and bind to it a `sequnce` of transform op. This is what I was thinking.

**Comment by KavithaTipturMadhu** [comment]
Can you explain how we can match different parameters such as H/W size exactly using transforms? Wouldn't a transform-generator be more suitable in this case?

**Comment by chelini** [comment]
Replying in reverse order. I don't exclude any transform-generator in the future, after all transform IR is an IR so we can build it. I just don't see the need short term. I believe we can find a way if needed, why do we need to match exactly H and W? Currently you can match based on op name, various attributes, interface and result types. I guess a broken why is to pass the size of H and W as attributes.

**Comment by chelini** [comment]
The main reasons why I am pushing for a transform only approach:
1. Linalg is moving to it, we need to follow
2. We can share optimization with others (assuming we can also convince them to have our transforms ops - which are only `map_to_brgemm` or `map_to_gemm` all the rest is upstream)
3. We avoid having rather complicated passes and instead we have a set of composable building blocks. User like Alex can just plug the optimization they want or generate them in some way.
4. It mitigate the pass order issue we have today.

**Comment by chelini** [comment]
Seems we reach an agreement. We will drop the c++ passes and drive all the optimization using transform. We will provide some default transforms in case the user does not specify any. We will proceed as follow: 1. mirror all the passes-based test to transform. 2. Add default transforms and drop c++ passes. At the end we will have only 1 pass: `tpp-opt --optimize-using-transform` (or something similar).

**Comment by rengolin** [comment]
After some conversations on IREE's Discord channel, I want to make it clear there is one important condition on this issue: we must still have a pass that will add the transforms on IR that doesn't have them yet.

This isn't anything new, it's just the current _analysis_ passes printing our their output in transform dialect.

The pass that would detect the correct pack/unpack to apply will instead, emit a transform match + pack. Remaining passes would just use those blocks to emit all remaining transforms necessary. Most of them can be hard-coded in a single pass.

Without this, we'd need experts to annotate the IR with the _right_ transforms. That's not only undocumented and not obvious, it's also against the main objective of this project, to automatically detect those.

Not having them now would mean a _regression_ in functionality, and we can't have that.

**Comment by rengolin** [comment]
Spoke to @chelini today and cleared a few things...

First, the old tests were passing arguments to the TPP passes, pretty much like the transforms now have the same arguments, which means we weren't _detecting_ them, just passing as arguments. In that sense, there is no _regression_ per se.

Also, the tests have 1-to-1 transform to function (via split IR flag) and that's very fragile, because we don't know how  multiple transform blocks for a single function will behave. This isn't a matter for this issue, it's something that #192 and #190 should test.

Here, we just need to create a pre-transform pass with the same arguments as before, but without doing anything, just filling up the transform blocks. An interim state is to have all transforms injected into the code and not need the pre-pass. In the end, many tests can continue with just transforms (for example, those that use split IR), but we must have some larger tests (ex. MLP, Conv, Attention) without a transform block, relying on the pre-pass to fill that up with the same arguments.
