### ISSUE TITLE
Move optimization passes on linalg to use transform

### ISSUE THREAD

**Issue by chelini** [plaidml/tpp-mlir#203]
As described in the RFC (https://github.com/plaidml/tpp-mlir/issues/134) we will move the optimization pipeline to use transform only. The following steps need to be taken:

Move optimization passes on linalg to use transform (packing, mapping convs to matmul or brgemm). This is done, see: [ceb85346dc2a3ee2e6f4d6a8a62add8ad7410000](https://github.com/plaidml/tpp-mlir/commit/ceb85346dc2a3ee2e6f4d6a8a62add8ad7410000), https://github.com/plaidml/tpp-mlir/commit/e2685bd2ec1e8270e439baa1a63859e2802b929e, https://github.com/plaidml/tpp-mlir/commit/e4e2d5a56e14dc09b84ead14b870e1644e8ad495). [Done]

**Comment by rengolin** [comment]
To clear the confusion on #134, this work has moved the "hard-coded" information (tile sizes, etc) per test from the pass argument to the transform block in the same IR.

It has not changed how the pass is able or not to "identify" shapes and passes (it wasn't, still isn't).

It makes it clear that a transform is for a piece of code, and it's undefined behaviour if there are two ops with the same properties but different shapes in the same IR. Before, it was the same, but unclear, now, because of the transform block, it is clear.

**Comment by rengolin** [comment]
Added issues for the other items that were in a checklist so we can close this one as done.
