### ISSUE TITLE
Add a pass to vectorize tensor.pack and tensor.unpack ops

### ISSUE THREAD

**Issue by chelini** [plaidml/tpp-mlir#279]
Provide a conversion for tensor.pack and tensor.unpack to the vector dialect. Similar to: https://github.com/iree-org/iree/pull/11838/commits

**Comment by rengolin** [comment]
As discussed in the meeting, this should be low priority, as we're going to pack the weight tensors at compile time and only input/output at runtime, if necessary.

**Comment by alheinecke** [comment]
Agree. The only thing that puzzles me: for F32 the pack/unpack should map to sequence of identity TPP (for NHWC/RSCK layout) and for BF16 to identity and norm->vnni TPP. We mustn't add vectoriztion passes, but fix mapping to TPP (as PlaidML was doing). However, even the latter has right now diminishing ROI as we actually should see only one pack on activations in the beginning and one unpack in the end of the execution, as @rengolin  mentioned above.

**Comment by rengolin** [comment]
It could be a good stepping stone to lower to TPP packing now, so that we get them "fast" even if not constant, and then later, we work on reducing the runtime packs. This should completely rid the need to do any kind of vectorization on our side.

I've created #290 to handle the identity lowering and #291 for the constant packing.
