### ISSUE TITLE
Perf dialect generating unrealized casts

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#449]
On some examples (which?) using the perf dialect to measure performance and calculation of mean/stdev. We need to investigate and fix.

@KavithaTipturMadhu please add here an example of the IRs you're working on.

@adam-smnk

**Comment by adam-smnk** [comment]
The unrealized cast in the functions generated by `perf` dialect were a bit of a red herring. The reported issue's root cause was more general caused by some poor interaction between backend passes invoked by `tpp-run` (see `MLIRBench::finalize`).
The new order of the backend passes seems to solve the issue for now.
