### ISSUE TITLE
[RFC] Benchmark kernels structure

### ISSUE THREAD

**Issue by adam-smnk** [plaidml/tpp-mlir#488]
We need to align in terms of how we write our test kernels, especially input IR that serves as our performance benchmarks (`benchmarks/mlir/*.mlir`) and larger models we use to manually evaluate quality of our passes (`test/Models`).
Currently, these MLIR IR files are a collection of random tests written at different point of our tensor compiler development. As our assumptions and constantly evolve, the test kernel also have to be updated and adapted to present times.

Here, I want to define and show some examples of how these test IR kernel should be structured such that:
1. We do not keep chasing unrealistic edge cases and complex IR structures that are unlikely to be even generated by automated front-ends.
2. Performance results represent realistic numbers i.e., if some memory allocations for intermediate results are unavoidable, then we have to pay the price and it should reflected in the measurements.
3. The test kernels are well defined which ensures semantic correctness (they represent exactly and only what we want to measure) and the IR is less susceptible to upstream changes (e.g., an explicit `alloc` will always* remain in its place - *subject to some optimizations that specifically target `alloc`s).

### Kernel inputs and outputs
All arguments of a kernel function (inputs) should be treated as constant/read-only values. No operation should write to any of the function arguments and the function arguments should not be used for `outs` of any up. This also ensures that bufferization does not use kernel arguments as output buffers at memref level.
The benchmarking framework (part of `tpp-run`) will still automatically allocate the input buffers based on the kernel arguments and random initialize them when requested.

All the significant results of a kernel function (outputs) e.g., values to be printed for `FileCheck` or just the final computed value, should have their buffers allocated within the kernel and be returned at the end of the kernel via `func.return`/`return` op. The destination passing should not be used for the kernel outputs.
This applies to both tensors and memrefs. If there are multiple values of interest, they all should be returned from a kernel which will result in multi-result function call `%out:N = func.call`.
The benchmarking framework (part of `tpp-run`) will automatically handles lifetime of the returned buffers. Note that currently there is no support for multi-return kernels but it can be added when needed.

#### An example of single-return kernel
```
func.func @entry(%A: tensor<48x96xf32>, %B: tensor<96x64xf32>) -> tensor<48x64xf32> {
  %0 = tensor.empty() : tensor<48x64xf32>
  %C = linalg.matmul ins(%A, %B: tensor<48x96xf32>, tensor<96x64xf32>) outs(%0: tensor<48x64xf32>) -> tensor<48x64xf32>
  return %C : tensor<48x64xf32>
}
```

#### An example of multi-return kernel
```
func.func @entry(%A: tensor<48x96xf32>, %B: tensor<96x64xf32>, %D: tensor<96x64xf32>) -> (tensor<48x64xf32>, tensor<48x64xf32>) {
  %0 = tensor.empty() : tensor<48x64xf32>
  %C = linalg.matmul ins(%A, %B: tensor<48x96xf32>, tensor<96x64xf32>) outs(%0: tensor<48x64xf32>) -> tensor<48x64xf32>
  %E = linalg.matmul ins(%A, %D: tensor<48x96xf32>, tensor<96x64xf32>) outs(%0: tensor<48x64xf32>) -> tensor<48x64xf32>
  return %C, %E : tensor<48x64xf32>, tensor<48x64xf32>
}
```

### Intermediate results
All buffers needed to store intermediate results should be allocated and deallocated within the kernel itself and NOT passed as kernel arguments. This approach ensures that kernels are more realistic and the cost of memory management is not hidden.

This applies to both tensors through `tensor.empty()`, and memrefs through `memref.alloc`/`memref.dealloc`.

#### An example of kernel with an intermediate results
Tensor level:
```
func.func @entry(%A: tensor<32x32xf32>, %B: tensor<32x32xf32>, %D: tensor<32x16xf32>) -> tensor<32x16xf32> {
  %0 = tensor.empty() : tensor<32x32xf32>
  %C = linalg.matmul ins(%A, %B: tensor<32x32xf32>, tensor<32x32xf32>) outs(%0: tensor<32x32xf32>) -> tensor<32x32xf32>
  %1 = tensor.empty() : tensor<32x16xf32>
  %E = linalg.matmul ins(%C, %D: tensor<32x32xf32>, tensor<32x16xf32>) outs(%1: tensor<32x16xf32>) -> tensor<32x16xf32>
  return %E : tensor<32x16xf32>
}
```
Memref level:
```
func.func @entry(%A: memref<32x32xf32>, %B: memref<32x32xf32>, %D: memref<32x16xf32>) -> memref<32x16xf32> {
  %0 = memref.alloc() : memref<32x32xf32>
  linalg.matmul ins(%A, %B: memref<32x32xf32>, memref<32x32xf32>) outs(%0: memref<32x32xf32>)
  %1 = memref.alloc() : memref<32x16xf32>
  linalg.matmul ins(%0, %D: memref<32x32xf32>, memref<32x16xf32>) outs(%1: memref<32x16xf32>)
  memref.dealloc %0 : memref<32x32xf32>
  return %1 : memref<32x16xf32>
}
```

### Constant values
Constant values that are expected to be know to a kernel at compile time, such as MLP weights and biases, should be defined within the kernel function.
At tensor level, these values should be defined as `arith.constant` ops. At memref level, the constant values should be represented by module level `memref.global "private" constant` ops.

This approach eliminates the need to pass many inputs to the kernel and allows for more compile-time optimizations such as constant packing.

#### An example of kernel with an constant values
Tensor level:
```
func.func @entry(%input: tensor<48x96xf32>) -> tensor<48x64xf32> {
  %weights = arith.constant dense<0.100000e+00> : tensor<96x64xf32>
  %0 = tensor.empty() : tensor<48x64xf32>
  %C = linalg.matmul ins(%input, %weights: tensor<48x96xf32>, tensor<96x64xf32>) outs(%0: tensor<48x64xf32>) -> tensor<48x64xf32>
  return %C : tensor<48x64xf32>
}
```
Memref level:
```
memref.global "private" constant @__constant_96x64xf32 : memref<96x64xf32> = dense<1.000000e-01> {alignment = 64 : i64}
func.func @entry(%input: memref<48x96xf32>) -> memref<48x64xf32> {
  %weights = memref.get_global @__constant_96x64xf32 : memref<96x64xf32>
  %0 = memref.alloc() : memref<48x64xf32>
  linalg.matmul ins(%input, %weights: memref<48x96xf32>, memref<96x64xf32>) outs(%0: memref<48x64xf32>)
  return %0 : memref<48x64xf32>
}
```

### An MLP example using above conventions:
Explicit zero initialization of matmul buffer:
```
#map = affine_map<(d0, d1) -> (d0, d1)>

func.func @entry(%arg0: tensor<256x1024xf32>) -> tensor<256x1024xf32> {
  %zero = arith.constant 0.0 : f32
  %weights = arith.constant dense<0.010000e+00> : tensor<1024x1024xf32>
  %bias = arith.constant dense<0.100000e+00> : tensor<256x1024xf32>

  %res = tensor.empty() : tensor<256x1024xf32>
  %zeroInitRes = linalg.fill ins(%zero : f32) outs(%res : tensor<256x1024xf32>) -> tensor<256x1024xf32>
  %0 = linalg.matmul ins(%arg0, %weights : tensor<256x1024xf32>, tensor<1024x1024xf32>) outs(%zeroInitRes : tensor<256x1024xf32>) -> tensor<256x1024xf32>

  %res1 = tensor.empty() : tensor<256x1024xf32>
  %2 = linalg.generic {indexing_maps = [#map, #map, #map], iterator_types = ["parallel", "parallel"]}
  ins(%0, %bias : tensor<256x1024xf32>, tensor<256x1024xf32>) outs(%res1 : tensor<256x1024xf32>) {
    ^bb0(%in: f32, %in_0: f32, %out: f32):
      %add = arith.addf %in, %in_0 : f32
      linalg.yield %add : f32
  } -> tensor<256x1024xf32>

  %3 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel"]} ins(%2 : tensor<256x1024xf32>) outs(%res1 : tensor<256x1024xf32>) {
    ^bb0(%in: f32, %out: f32):
      %max = arith.maxf %in, %zero : f32
      linalg.yield %max : f32
  } -> tensor<256x1024xf32>
  
  return %3 : tensor<256x1024xf32>
}
```
Using `outs` as initial value at the tensor level for matmul buffer initialization:
```
#map = affine_map<(d0, d1) -> (d0, d1)>

func.func @entry(%arg0: tensor<256x1024xf32>) -> tensor<256x1024xf32> {
  %zero = arith.constant 0.0 : f32
  %weights = arith.constant dense<0.010000e+00> : tensor<1024x1024xf32>
  %bias = arith.constant dense<0.100000e+00> : tensor<256x1024xf32>
  
  %zeroInitRes = arith.constant dense<0.000000e+00> : tensor<256x1024xf32>
  %0 = linalg.matmul ins(%arg0, %weights : tensor<256x1024xf32>, tensor<1024x1024xf32>) outs(%zeroInitRes : tensor<256x1024xf32>) -> tensor<256x1024xf32>

  %res1 = tensor.empty() : tensor<256x1024xf32>
  %2 = linalg.generic {indexing_maps = [#map, #map, #map], iterator_types = ["parallel", "parallel"]}
  ins(%0, %bias : tensor<256x1024xf32>, tensor<256x1024xf32>) outs(%res1 : tensor<256x1024xf32>) {
    ^bb0(%in: f32, %in_0: f32, %out: f32):
      %add = arith.addf %in, %in_0 : f32
      linalg.yield %add : f32
  } -> tensor<256x1024xf32>

  %3 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel"]} ins(%2 : tensor<256x1024xf32>) outs(%res1 : tensor<256x1024xf32>) {
    ^bb0(%in: f32, %out: f32):
      %max = arith.maxf %in, %zero : f32
      linalg.yield %max : f32
  } -> tensor<256x1024xf32>
  
  return %3 : tensor<256x1024xf32>
}
```

**Comment by adam-smnk** [comment]
Any thoughts?
If (when?) there are no objections, I would propose to update our existing benchmark kernels to follow this convention.
Also, `tpp-run` will need a small tweak to stop leaking memory when the input IR is at tensor level - at the moment deallocation is inserted only when kernel starts at memref.

**Comment by rengolin** [comment]
Thanks for writing this down, we really need a policy on benchmarks.

A few inline comments...

> All arguments of a kernel function (inputs) should be treated as constant/read-only values.

Read-only yes, constants, not necessarily. But I'm not sure how we can control this at the IR level.

An easy (manual) way to check is to pass the kernel to `tpp-opt` and see if the lowering to memref has added `alloc+copy` on the inputs. If it did, then it's been written to inside the kernel.

> The destination passing should not be used for the kernel outputs. This applies to both tensors and memrefs.

This [example](https://github.com/plaidml/tpp-mlir/blob/main/test/Models/multi-head-attention.mlir#L33) was lowered from Tensorflow's BERT. If this hasn't been modified in any way (@nhasabni can you confirm this?), then TF expects the output to be an argument.

> The benchmarking framework (part of tpp-run) will automatically handles lifetime of the returned buffers.

We need to guarantee that the memref was allocated inside the kernel. If the return is from an input or an internal constant (say, global), then deallocating it would be an error.

If we allocate the output in the main wrapper and pass that to the kernel, we can guarantee where the allocation came from, bufferization won't need to create `alloc+copy` (because the arg isn't constant), we can safely reuse it inside the benchmark loop, and we can always deallocate it after printing/comparing.

> All buffers needed to store intermediate results should be allocated and deallocated within the kernel itself and NOT passed as kernel arguments. This approach ensures that kernels are more realistic and the cost of memory management is not hidden.

Yes! This is very important, as those costs will show up in full models and if we don't measure them now on small benchmarks, we'll have a hard time reaching performance on entire models.

Reuse of buffers is an optimisation that we have to do anyway, and if it's too hard to do at linalg level, we may be able to do it more easily at TPP level.

> Constant values that are expected to be know to a kernel at compile time, such as MLP weights and biases, should be defined within the kernel function.

Exactly!

```mlir
  %zeroInitRes = arith.constant dense<0.000000e+00> : tensor<256x1024xf32>
  %0 = linalg.matmul ins(%arg0, %weights : tensor<256x1024xf32>, tensor<1024x1024xf32>) outs(%zeroInitRes : tensor<256x1024xf32>) -> tensor<256x1024xf32>
```

This is invalid IR, as the `outs` is a constant. If you want a "binary" matmul (A*B), you need an `empty+fill(0)`. If you want a "ternary" matmul (A*B+C), you need the `C` to be writable (empty, previous result, args). 

Optimisations of that pattern could be:
* match a `gemm` with `BETA=0` and not `fill`.
* move the `addf` generic "above" `matmul` and not need to `zero`.
* match a `fused brgemm` etc.

If they're arguments, we need them not to be read-only, violating the first directive above. So, we either assume all arguments can be writable (inputs and outputs), or we allocate the temporaries (at least the first one) inside the kernel.

For the sole purpose of benchmarks, I think either strategy is good, because both will show the reuse of buffers, and only differ on one single point: whether they allocate _"the initial buffers"_ inside or outside of the kernel. 

All of the other allocations will remain inside the kernel and should be optimised whenever possible.

**Comment by nhasabni** [comment]
> This [example](https://github.com/plaidml/tpp-mlir/blob/main/test/Models/multi-head-attention.mlir#L33) was lowered from Tensorflow's BERT. If this hasn't been modified in any way (@nhasabni can you confirm this?), then TF expects the output to be an argument.

@rengolin [Original code that I pushed](https://github.com/plaidml/tpp-mlir/commit/176e80ac91d275a6fda00c1614c947304b97e1ef) actually had a clean signature that was following the ideas discussed here: `func.func @mha(%in:tensor<32x8x128xf32>) -> tensor<32x8x128xf32>`.

**Comment by adam-smnk** [comment]
> > This [example](https://github.com/plaidml/tpp-mlir/blob/main/test/Models/multi-head-attention.mlir#L33) was lowered from Tensorflow's BERT. If this hasn't been modified in any way (@nhasabni can you confirm this?), then TF expects the output to be an argument.
> 
> @rengolin [Original code that I pushed](https://github.com/plaidml/tpp-mlir/commit/176e80ac91d275a6fda00c1614c947304b97e1ef) actually had a clean signature that was following the ideas discussed here: `func.func @mha(%in:tensor<32x8x128xf32>) -> tensor<32x8x128xf32>`.

So this one is a bit of a red herring 😅 
I added the `output` to the kernel to try solve memory leaks. The `output` argument should be removed and by using consistent returns for outputs, we can prevent leaks by generating better kernel wrapper within `tpp-run`.

**Comment by rengolin** [comment]
> So this one is a bit of a red herring sweat_smile I added the `output` to the kernel to try solve memory leaks. The `output` argument should be removed and by using consistent returns for outputs, we can prevent leaks by generating better kernel wrapper within `tpp-run`.

I see, in this case we need to check the provenance of the pointer to make sure we can/have to deallocate it.

If the pointer was allocated inside the kernel, we "have to".

If the pointer was allocated outside of the kernel, we "may have to", but we can't do it twice.

If the pointer alias with an input, constant or global, "we cannot".

If the kernel originally allocated it, but optimisations moved to `in-place`, we may have to "remove" the deallocation (if any was added).

Or we can just **always** convert the return to the last argument _"inside `tpp-run`"_, so that we always write the right way and always control the provenance ourselves.

**Comment by rengolin** [comment]
Just did a test with `mlp-gen` and `tpp-opt` between manual packing, auto-packing and constant weights.

Our current benchmarks have manual packing, which generates "perfect code":
* No pack/unpack
* Single dispatch for each function
* Single invoke for each TPP op inside the parallel loop
* No `alloc` / `dealloc` calls whatsoever

Running the same `mlp-gen` without `--tiles` option, puts weight as arguments, when passing that through `tpp-opt` we get:
* Pack all for arguments (input, weights and output)
* Single dispatch/invoke
* One `alloc`/`dealloc` pair for each pack above
* Unpack for output before return

Changing the weights to constants, cleans up a bit and has no otherwise negative effect:
* Packing for input and output (still in args)
* Single dispatch/invoke
* No `alloc` for weights
* Unpacking for output before return

Making the output a local tensor (with zero fill), we get the expected unpacked code:
* Packing only for input
* An unpacked alloc for the output (for the result of the unpack later)
* Single dispatch/invoke
* No `alloc` for weights
* Unpacking for output before return

Allocating the output in the kernel creates a problem for the caller that needs to deallocate it before the next call. It may be avoided if the dispatcher reuses the same buffer, but then we need to treat it differently when packing, ie. change the argument's shape, while still keeping the original return shape, and having the caller to zero in between calls. 

Since this is something we can't reliably do with generic code, and one single allocation doesn't kill performance, we may overlook this issue. Using stack space doesn't work unless it's caller stack and not calee stack. It also may blow up the stack depending on the size of the return tensor.

However, keeping the packed generation is still a good metric, because it gives us an idea of how fast a single layer can be, when all allocation costs are factored out (usually absorbed for large models if done right).

If we change the output to return, we'll have a regression on the current layer benchmarks. If we want both styles, we'll have to find a way to communicate this to `tpp-run` to avoid memory leaks.

@adam-smnk 

Curiously, the packing pass doesn't quite make the same shapes as the generator's, when making the output a local constant. Needs further investigation.

@chelini

**Comment by adam-smnk** [comment]
> If we change the output to return, we'll have a regression on the current layer benchmarks. If we want both styles, we'll have to find a way to communicate this to tpp-run to avoid memory leaks.

Agree here. Clearly we need to support both style (return and destination passing) as it allows us to measure different things. 

Currently `tpp-run` generates the kernel wrapper at the beginning before running any passes. To solve the deallocation issue, it will probably be easier to run an extra cleanup pass after the default pipeline (once we cross bufferization boundry) that deallocates function returns.
It is not a generic pass that should be integrated into the pipeline but an extra utility logic applied by `tpp-run`.

> Curiously, the packing pass doesn't quite make the same shapes as the generator's, when making the output a local constant. Needs further investigation.

Could you add an example?

**Comment by rengolin** [comment]
> > Curiously, the packing pass doesn't quite make the same shapes as the generator's, when making the output a local constant. Needs further investigation.
> 
> Could you add an example?

It's not clear to me where it is coming from. I sent you guys a reproducer.

**Comment by rengolin** [comment]
@adam-smnk I think we're done with this issue, right?

**Comment by adam-smnk** [comment]
Many ideas have been incorporated or further evolved. Benchmarks have been moved to rely on `mlir-gen` than ensure proper/consistent IR structure. Otherwise, kernels coming from external frontends are used (e.g., MHA kernels) which structure is dictated by external factors.

Future kernel structure changes should be mostly driven by IR coming from external frameworks or by changes to `mlir-gen`.
If needed, this can be iterated on in separate issues.

Closing this issue.
