### ISSUE TITLE
[RFC] Handling VNNI

### ISSUE THREAD

**Issue by chelini** [plaidml/tpp-mlir#557]
Currently, we VNNI pack at the tensor level. Out entry function is: https://github.com/plaidml/tpp-mlir/blob/d09d6272e0c1028bfbf871648af67b48da7c0db3/lib/TPP/ToBlockLayoutAndBack.cpp#L761 

This is inconvenient because we need to handle 3d dimensional tensor in tpp.brgemm and tpp.gemm as we change the shape of the B operand. Handling 3d tensor needs to some changes in the op verifier and lowering, see for example: https://github.com/plaidml/tpp-mlir/blob/d09d6272e0c1028bfbf871648af67b48da7c0db3/lib/TPP/Dialect/Tpp/TppOps.cpp#L275

But when do we do VNNI packing? At the tpp level? If we do it in the tpp dialect (i.e., at the memref level), we will still have the verification problem. We could think of moving VNNI to XSMM:

```
memref.global "private" constant @__constant_4x32x32xbf16 : memref<4x32x32xbf16> = dense<1.000000e+00> {alignment = 64 : i64}
func.func @matmul_eletwise(%arg0: memref<64x128xbf16>, %arg1: memref<64x64xbf16>) -> memref<2x2x32x32xbf16> {
  %c4_i64 = arith.constant 4 : i64
  %0 = memref.get_global @__constant_4x32x32xbf16 : memref<4x32x32xbf16>
  // pack allocation 
  %alloc = memref.alloc() {alignment = 64 : i64} : memref<2x4x32x32xbf16>
  // pack allocation 
  %alloc_0 = memref.alloc() {alignment = 64 : i64} : memref<2x2x32x32xbf16>
  scf.forall (%arg2, %arg3) in (2, 2) {
    %subview = memref.subview %alloc[%arg2, 0, 0, 0] [1, 4, 32, 32] [1, 1, 1, 1] : memref<2x4x32x32xbf16> to memref<4x32x32xbf16, strided<[1024, 32, 1], offset: ?>>
    %subview_1 = memref.subview %alloc_0[%arg2, %arg3, 0, 0] [1, 1, 32, 32] [1, 1, 1, 1] : memref<2x2x32x32xbf16> to memref<32x32xbf16, strided<[32, 1], offset: ?>>
    
    // need to "fix-up" the dispatch -> flags(vnni_b)
    %1 = xsmm.brgemm.dispatch [32, 32, 32, 32, 32, 32] flags = (none) data_type = bf16
    
    // vnni packing for b.
    %operand_b = xsmm.vnni_2 %0 : memref<4x32x32xbf16> -> memref<4x16x32x2xbf16>
    xsmm.brgemm(data_type = bf16, %1, %subview, %0, %subview_1, %c4_i64) : (i64, memref<4x32x32xbf16, strided<[1024, 32, 1], offset: ?>>, memref<4x32x32xbf16>, memref<32x32xbf16, strided<[32, 1], offset: ?>>, i64) -> ()
    %2 = xsmm.unary.dispatch relu [32, 32, 32, 32] flags = (none) data_type = bf16
    xsmm.unary relu(data_type = bf16, %2, %subview_1, %subview_1) : (i64, memref<32x32xbf16, strided<[32, 1], offset: ?>>, memref<32x32xbf16, strided<[32, 1], offset: ?>>) -> ()
    }
    memref.dealloc %alloc : memref<2x4x32x32xbf16>
    return %alloc_0 : memref<2x2x32x32xbf16>
}
```
This requires a) a pass to relayout in VNNI the operands. b) re-work constant folding to operate on memref.global c) a fix up pass for the emitted dispatch that need to be updated with the vnni flags. 

@rengolin @alheinecke @KavithaTipturMadhu and @adam-smnk

**Comment by rengolin** [comment]
There are two cases: constant (ex. weights) and non constant (ex. inputs).

For constants, we only "pack vnni" at the end, re-packing the constants at compile time. For non constants, we need to add the operation (`NORM_TO_VNNI`). For both, we need to adjust the surrounding ops accordingly.

If we do in `tpp`, we can lower to `xsmm` without issues, with the right shapes and flags, but we need to support different shapes in `tpp`. 

If we do in `xsmm`, we'll need to investigate every dispatch/invoke pair and change their flags accordingly. This must be done before hoisting and collapsing dispatches, to avoid getting in a situation where a single dispatch is used by vnni and non-vnni invokes.

Regardless of where we do it, `xsmm` ops will have to have both versions, perhaps even a validation on the invoke checking that the dispatch (producer of the first argument) has the right flag.

For the constant case, the constant memref can only be changed if there are no other users, or if *all* other users are also being converted to vnni shape. So this needs an analysis pass before to make sure the change is safe. Once done, we can just change the arguments.

For the non-constant case, it will have been packed beforehand. On the `tpp` case, the pack will have been lowered to a loop of `tpp.copy` calls. We need to convert them to `tpp.vnni_pack` (and change its output shape), which it should be enough to pass to the operation getting a vnni argument.

If we do this at the `xsmm` level, the calls will have already been lowered to `xsmm.unary` which will be harder to match to a copy (but not impossible). The XSMM operation is still the same (`IDENTITY`) but the flag now is `NORM_TO_VNNI`. This is more fragile, but could be done.

The complexity here is that you need to get the operand that will be vnni, follow it back to its producer and find the users that are inside a loop being packed (which isn't a single op anymore). This is true on both `tpp` and `xsmm` if we lower it as a loop of `tpp.copy` calls. 

If we had a `tpp.pack` operation, this would be simpler, but implementing the `tpp.pack` operation is far from simple and comes with a large cost to the design of the rest of the dialect, so I don't think we should consider it.

If all else fails, adding a vnni pack into the inner loop wouldn't be a super expensive op anyway (mostly in registers or L1), so we could start that way and consider the rest as an optimization.

From this optics, I don't see a huge addition in complexity by running this at the `xsmm` level instead of `tpp`, and it would keep the `tpp` dialect simpler for the architectures that don't need it (ex. GPUs).

**Comment by rengolin** [comment]
> b) re-work constant folding to operate on memref.global

I've implemented the random tensor function on both local and global constants and they're very similar. I think we can find a template trick to have a single implementation for both.

**Comment by rengolin** [comment]
@chelini, was this solved last week with your re-working of the VNNI packing?

**Comment by chelini** [comment]
> @chelini, was this solved last week with your re-working of the VNNI packing?

Yes, we can close.
